### ISSUE TITLE
Authorize GetResult method

### ISSUE THREAD

**Issue by mrweiland** [JayKrishnareddy/JWTAuth_Validation#1]
I get everything to run but when i try to GetResult with my authorization key set in swagger i get invalid token. 
This code:
 ```
[Authorize(AuthenticationSchemes = Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerDefaults.AuthenticationScheme)]
        [HttpGet(nameof(GetResult))]
        public IActionResult GetResult()
        {
            return Ok("API Validated");
        }
```

I expect that i would say ok everything looks good but i get in call from swagger
```
content-length: 0 
 date: Tue,28 Sep 2021 17:09:32 GMT 
 server: Kestrel 
 www-authenticate: Bearer error="invalid_token" 
```

I also tried to clone your code - but i get same error there. Is there something i missing here? First time implementing JWT in c#.

**Comment by mrweiland** [comment]
Well - im used to consume api  of course i need to take the key from the login into Bearer authorization :)

**Comment by JayKrishnareddy** [comment]
In order to get the token you need to pass the username and password to Login API and in response, you will receive the token. Pass the token once after you click on the Authorize button  - "Bearer {token}".

Please go through the below article in detail 

https://www.c-sharpcorner.com/article/jwt-validation-and-authorization-in-net-5-0/

Hope this clears your question related to token.
